### ISSUE TITLE
builder object has no attribute tempdir

### ISSUE THREAD

**Issue by graik** [strubelab/multiprot#5]
The following error is raised during exception handling of builder test cases (when ranch is not installed):

```py
Traceback (most recent call last):
  File "/Volumes/data/raik/py/multiprot/multiprot/builder.py", line 184, in test_example5
    build = call.build()
  File "/Volumes/data/raik/py/multiprot/multiprot/builder.py", line 92, in build
    self.cleanup()
  File "/Volumes/data/raik/py/multiprot/multiprot/builder.py", line 41, in cleanup
    T.tryRemove(self.tempdir, tree=True)
AttributeError: 'Builder' object has no attribute 'tempdir'
```

Looks like the self.tempdir variable has been removed at some point.

**Comment by guzmanfj** [comment]
I think that this error popped up for me too at some point, and if I remember correctly it was because in the Executor wrapper for pulchra I was calling the parent `__init__` method without the `tempdir` argument, so the wrapper was taking `tempdir` as the system's "parent" temporary directory and deleting it after running pulchra, with all the other temporary folders in it (including the one the builder module was using).

I haven't seen that error since, but if you encounter it again let me know.

**Comment by graik** [comment]
But the error is not about a missing directory but about a missing variable. The builder object is expected to have a variable `tempdir` which doesn't exist. The current version of builder.py doesn't have the self.tempdir any longer though.

**Comment by guzmanfj** [comment]
Oh I see... mm well I have not seen that error, and I don't have a cleanup method anymore in builder.py haha so maybe you could try in the newest version of the dev branch?
